<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- saved from url=(0115)http://stackoverflow.com/questions/35046573/valueerror-must-be-a-coordinate-pair-or-point-in-python-for-lat-and-lon -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style>div,iframe { top: 0; position:absolute; }</style></head><body style="margin:0px;padding:0px;"><script type="text/javascript">var divName = "adzerk398394337";var inFIF=true;var inDapIF = true;</script><ins class="dcmads" style="display: inline-block; width: 728px; height: 90px; text-decoration: none;" data-dcm-placement="N233401.1948300STACKOVERFLOW/B9334612.127025567" data-dcm-rendering-mode="iframe" data-dcm-https-only="" data-dcm-click-tracker="http://engine.adzerk.net/r?e=eyJhdiI6NjMzMDUsImF0Ijo0LCJidCI6MCwiY20iOjQ5MTE0OSwiY2giOjExNzgsImNrIjp7fSwiY3IiOjE3MjEyODgsImRpIjoiZTM2YWI5ZjRkOGNjNGEwYjg4NDQ5NTM2ZDJjY2FlMmIiLCJkbSI6MSwiZmMiOjIwNDM3MjAsImZsIjoyNDY1OTkxLCJpcCI6IjIxOC4yNDguNDYuMTA3Iiwia3ciOiJweXRob24scGFpcixnZW9weSx4LXVzZXItcmVnaXN0ZXJlZCIsIm1rIjoicHl0aG9uIiwibnciOjIyLCJwYyI6NC41LCJlYyI6NC41LCJwciI6NzY1LCJydCI6MiwicmYiOiJodHRwczovL3d3dy5nb29nbGUuY28uaW4vIiwic3QiOjgyNzcsInVrIjoidWUxLWY3YzcxYjczYjRjZjQxZmRhZjBjYjdmODliMGNiNmNhIiwiem4iOjQzLCJ0cyI6MTQ3NzU3NDc3NTI1MywiYmYiOnRydWUsInBuIjoiYWR6ZXJrMzk4Mzk0MzM3IiwidXIiOm51bGx9&amp;s=28rXQTvwCHHvzBlpBks5gMt7JdY&amp;url=" data-dcm-processed="y">
  <script src="./dcmads.js.download"></script><script src="./impl_v35.js.download"></script><iframe marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="./B9334612.html" style="width: 100%; height: 100%; border: 0px; margin: 0px; padding: 0px;"></iframe>
</ins></body></html>